### ISSUE TITLE
Supporting arm64; a checklist

### ISSUE THREAD

**Issue by vielmetti** [etcd-io/etcd#10318]
From the docs:

> For etcd to officially support a new platform as stable, a few requirements are necessary to ensure acceptable quality:

This issue tracks those elements required for "stable" support for arm64, and identifies the checklist of support requirements; it's similar to https://github.com/etcd-io/etcd/issues/9409 (IBM s390x) or the work done to get ppc64le supported.

* [ ] An "official" maintainer for the platform with clear motivation; someone must be responsible for taking care of the platform.
* [x] Set up CI for build; etcd must compile. (Done since #7714 , work by @glevand )
* [ ] Set up CI for running unit tests; etcd must pass simple tests.
* [ ] Set up CI (TravisCI, SemaphoreCI or Jenkins) for running integration tests; etcd must pass intensive tests.
* [ ] (Optional) Set up a functional testing cluster; an etcd cluster should survive stress testing.

**Comment by vielmetti** [comment]
Affirming that there is still interest in this, to defeat the stale bot.
