### ISSUE TITLE
v0.4.6 flag compatibility

### ISSUE THREAD

**Issue by bcwaldon** [etcd-io/etcd#1155]
Below is the list of all v0.4.6 flags and the current state of them in v0.5.0:
- [x] -addr -- #1220
- [x] -bind-addr -- #1220
- [X] -ca-file
- [X] -cert-file
- [X] -cluster-active-size -- marked as deprecated
- [X] -cluster-remove-delay -- marked as deprecated
- [X] -cluster-sync-interval -- marked as deprecated
- [X] -cors
- [x] -config
- [X] -data-dir
- [x] -discovery -- @xiangli-cmu is working on it - #1009 
- [X] -force -- marked as deprecated
- [X] -h/-help
- [X] -key-file
- [X] -max-result-buffer -- marked as deprecated
- [X] -max-retry-attempts -- marked as deprecated
- [x] -name -- @philips is working on it - #1147 
- [x] -peer-addr -- #1220
- [x] -peer-bind-addr -- #1220
- [X] -peer-ca-file
- [X] -peer-cert-file
- [X] -peer-key-file
- [X] -peer-heartbeat-interval -- marked as deprecated
- [X] -peer-election-timeout -- marked as deprecated
- [x] -peers-file
- [x] -peers 
- [X] -retry-interval -- marked as deprecated
- [X] -snapshot -- marked as deprecated
- [X] -snapshot-count
- [X] -v/-vv -- marked as deprecated
- [x] -version
