### ISSUE TITLE
[lint] make verify-lint doesn't verify {api,server,client,...} modules 

### ISSUE THREAD

**Issue by fuweid** [etcd-io/etcd#16610]
### Which github workflows are flaking?

.github/workflows/static-analysis.yaml

### Which tests are flaking?

make verify-lint

### Reason for failure (if possible)

golanglint-ci doesn't support multiple modules in one repo. We need to chdir and run the lint for each module.

```bash
# in root
➜  etcd git:(main) make verify-lint
golangci-lint run --config tools/.golangci.yaml

# in server module
➜  server git:(main) golangci-lint run --config ../tools/.golangci.yaml
storage/datadir/datadir_test.go:20: File is not `goimports`-ed with -local go.etcd.io (goimports)
        "github.com/stretchr/testify/assert"
storage/backend/backend_bench_test.go:22: File is not `goimports`-ed with -local go.etcd.io (goimports)
        "github.com/stretchr/testify/assert"
storage/backend/backend_test.go:24: File is not `goimports`-ed with -local go.etcd.io (goimports)
        "github.com/stretchr/testify/assert"
storage/backend/hooks_test.go:22: File is not `goimports`-ed with -local go.etcd.io (goimports)
        "github.com/stretchr/testify/assert"
mock/mockwait/wait_recorder.go:37:33: unused-parameter: parameter 'id' seems to be unused, consider removing or renaming it as _ (revive)
func (w *waitRecorder) Register(id uint64) <-chan any {
                                ^
```

### Work items

- [x] goimports https://github.com/etcd-io/etcd/pull/16628
- [x] ineffassign https://github.com/etcd-io/etcd/pull/16605
- [x] revive https://github.com/etcd-io/etcd/pull/16634
- [x] staticcheck https://github.com/etcd-io/etcd/pull/16626
- [ ] stylecheck https://github.com/etcd-io/etcd/pull/16638
- [ ] unused https://github.com/etcd-io/etcd/pull/16638
- [ ] unconver https://github.com/etcd-io/etcd/pull/16638
