### ISSUE TITLE
Address CVE-2023-45288

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#17703]
### What would you like to be added?

CVE-2023-45288 / [GO-2024-2687](https://pkg.go.dev/vuln/GO-2024-2687) was recently published. We need to:

### Go version bump

- [x] main: #17707
- [x] release-3.5: #17708
- [x] release-3.4: #17709
- [x] ~Update CHANGELOG: done in #17707~
- [x] Raft: etcd-io/raft#191
- [x] bbolt 1.3: etcd-io/bbolt#713
- [x] bbolt main: etcd-io/bbolt#712

### Bump `golang.org/x/net` from 1.22.1 to 1.22.2

- [x] ~main: #17707~
- [x] ~release-3.5: #17708~
- [x] ~release-3.4: #17709~

### Why is this needed?

To improve security and address the CVE. And to keep the Go version up to date.

**Comment by henrybear327** [comment]
I can work on the first 4 items!

**Comment by ahrtr** [comment]
We also need to update bbolt (including both main and release-1.3) and raft.

**Comment by rissh** [comment]
Hello everyone,

I'm diving into updating dependencies for CVE-2023-45288 / GO-2024-2687. Excited to give it a shot! If anyone wants to join or has advice, let me know.

**Comment by henrybear327** [comment]
> Hello everyone,
> 
> I'm diving into updating dependencies for CVE-2023-45288 / GO-2024-2687. Excited to give it a shot! If anyone wants to join or has advice, let me know.

Hey @rissh, 

I have already created all the PRs!

**Comment by rissh** [comment]
Hi @henrybear327 ,

Thank you for taking the initiative to create the PRs! Your efforts are commendable. I'm glad to see progress on this front.
I'm also eager to contribute and collaborate on this issue. Feel free to reach out if you require any assistance or support.

Thanks again.

**Comment by henrybear327** [comment]
> ### What would you like to be added?
> CVE-2023-45288 / [GO-2024-2687](https://pkg.go.dev/vuln/GO-2024-2687) was recently published. We need to:
> 
> * [ ]  update `main`'s branch Go version from 1.22.1 to 1.22.2
> * [ ]  update `release-3.5` from 1.21.8 to 1.21.9
> * [ ]  update `release-3.4` from 1.21.8 to 1.21.9
> * [ ]  update CHANGELOG
> * [ ]  update `main`'s `golang.org/x/net` from v0.22.0 to v0.23.0
> 
> The severity hasn't been published yet. So, I'm unsure if we should update `golang.org/x/net` in release-3.4/3.5. However, it may be a good idea as the `govuln` check will fail.
> 
> ### Why is this needed?
> To improve security and address the CVE. And to keep the Go version up to date.

The vulnerability scan on CI will [report an error](https://github.com/etcd-io/etcd/actions/runs/8551422689/job/23430401128), thus, the decision is made to also upgrade `golang.org/x/net`.  

Log extract:
```
go: downloading golang.org/x/vuln v1.0.4
go: downloading golang.org/x/mod v0.14.0
go: downloading golang.org/x/tools v0.1[7](https://github.com/etcd-io/etcd/actions/runs/8551422689/job/23430401128#step:6:8).0
go: downloading golang.org/x/sync v0.6.0
Scanning your code and 504 packages across 77 dependent modules for known vulnerabilities...

=== Symbol Results ===

Vulnerability #1: GO-2024-26[8](https://github.com/etcd-io/etcd/actions/runs/8551422689/job/23430401128#step:6:9)7
    HTTP/2 CONTINUATION flood in net/http
  More info: https://pkg.go.dev/vuln/GO-2024-2687
  Module: golang.org/x/net
    Found in: golang.org/x/net@v0.22.0
    Fixed in: golang.org/x/net@v0.23.0
```

**Comment by ivanvc** [comment]
@henrybear327, I just saw that you bumped the dependency and Go in tandem. Thanks, I'll update the to-do list from the description.

**Comment by henrybear327** [comment]
> @henrybear327, I just saw that you bumped the dependency and Go in tandem. Thanks, I'll update the to-do list from the description.

Hey @ivanvc, 

Sorry that I probably should have done it in 2 PRs instead of 1. I will keep that in mind next time! :)

**Comment by ivanvc** [comment]
With all subtasks completed. I'll go ahead and close this issue. Thanks, @henrybear327 and @MrDXY, for working on this :bow:

**Comment by ivanvc** [comment]
Reopening as #17708 only partially addressed the issue.

@jmhbnz, would we need a new CHANGELOG entry for 3.5 for this?

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting, the work has been completed for this so we can close. We need to push ahead with `3.5.15` to release this.
