### ISSUE TITLE
Bump go to 1.21.12 / 1.22.5

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#18269]
### What would you like to be added?

Go 1.21.12 and 1.22.5 include a fix for the [GO-2024-2963](https://pkg.go.dev/vuln/GO-2024-2963) vulnerability in `net/http`. This update should be included in the next 3.5 release.

Completion tracking below:

- [x] `main`: go v1.22.5 - #18270
- [x] `release-3.5`: go v1.21.12 - #18271
- [x] `release-3.4`: go v1.21.12 - #18272
- [x] `CHANGELOG` - #18282
- [x] `etcd-io/bbolt` `main`: go v1.22.5 - etcd-io/bbolt#784
- [x] `etcd-io/bbolt` `release-1.3`: v1.21.12 - etcd-io/bbolt#785
- [x] `etcd-io/raft` `main`: go v1.22.5 - etcd-io/raft#205

Refer to previous issues and its pull requests as a reference, i.e., https://github.com/etcd-io/etcd/issues/17964

### Why is this needed?

To improve the project security and address the CVE.

**Comment by ivanvc** [comment]
I'm unsure if we should open this as a `good first issue` or if we prefer someone with bandwidth to do it soon so we don't hold up #18247.

**Comment by thedtripp** [comment]
I'd like to help with this. It looks like may take multiple PRs so let me know where I can assist.

**Comment by ivanvc** [comment]
/assign @thedtripp

Thank you. You can start with this repository (main, release-3.5, and release-3.4). I'd hold bbolt and raft until we have @ahrtr's input.

**Comment by ivanvc** [comment]
@thedtripp, we still don't have documentation for this. I was trying to find the issue where I commented on updating the Go version with our latest scripts. However, you now just need to update the `.go-version` file and then run `make fix` (which runs `./scripts/sync_go_toolchain_directive.sh`). 

It is backported to 3.4 and 3.5, so it should be the same process for all the branches.

**Comment by thedtripp** [comment]
@ivanvc Ok. I'll give that a _go_ on the main branch first. Thanks

**Comment by ahrtr** [comment]
> * [ ]  `etcd-io/bbolt` `release-1.3`: v1.21.12 (do we want to update 1.3?)
> * [ ]  `etcd-io/raft` `main`: go v1.22.5 (do we want to update raft?)

I think so.

**Comment by ivanvc** [comment]
@thedtripp, could you open a PR to update 3.4/3.5 CHANGELOGs? Would you also want to help with bbolt and raft? Or should we open it up for another contributor?
Thank you.

**Comment by thedtripp** [comment]
> @thedtripp, could you open a PR to update 3.4/3.5 CHANGELOGs? Would you also want to help with bbolt and raft? Or should we open it up for another contributor?
> 
> Thank you.

Yes, I'd like to help with those. I'll look into it later today.

**Comment by ivanvc** [comment]
Thanks, @thedtripp. Closing this as there are no outstanding tasks.
