### ISSUE TITLE
Bump Go to 1.21.13/1.22.6

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#18419]
### What would you like to be added?

Go versions 1.21.13 and 1.22.6 were released two days ago. Although they don't include any security fixes, our [guideline](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#golang-versions) states that we aim to keep the Go version up to date.

Completion tracking below:

- [x] `main`: go v1.22.6 - #18420
- [x] `release-3.5`: go v1.21.13 - #18421
- [x] `release-3.4`: go v1.21.13 - #18422
- [x] `CHANGELOG` - #18423
- [x] `etcd-io/bbolt` `main`: go v1.22.6 - etcd-io/bbolt#813
- [x] `etcd-io/bbolt` `release-1.3`: v1.21.13 - etcd-io/bbolt#814
- [x] `etcd-io/raft` `main`: go v1.22.6 - etcd-io/raft#210
- [x] `etcd-io/gofail` `main`: go v1.22.6 - etcd-io/gofail#77

Refer to previous issues and their pull requests as a reference, i.e., #18269.

### Why is this needed?

To keep the project up to date with the latest released Go version.

**Comment by ivanvc** [comment]
@henrybear327, do you want to work on this?

**Comment by henrybear327** [comment]
/assign @henrybear327 

@ivanvc yes I do!

**Comment by henrybear327** [comment]
@ivanvc we probably would like to 
- add `etcd-io/gofail` to the list
- move CHANGELOG to its dedicated category, since all 4 repos need to have their respective CHANGELOG updated

What do you think :)

**Comment by ivanvc** [comment]
> add `etcd-io/gofail` to the list

Added!

> move CHANGELOG to its dedicated category, since all 4 repos need to have their respective CHANGELOG updated

Because the other repositories have fewer releases and contributors, I noticed that, at least for Bbolt, Benjamin does it when preparing the next release.

**Comment by henrybear327** [comment]
> > add `etcd-io/gofail` to the list
> 
> Added!

Thanks!
> 
> > move CHANGELOG to its dedicated category, since all 4 repos need to have their respective CHANGELOG updated
> 
> Because the other repositories have fewer releases and contributors, I noticed that, at least for Bbolt, Benjamin does it when preparing the next release.

Oops, I have done it for all...

**Comment by henrybear327** [comment]
We can close this issue now! :) Thanks everyone for the quick review and comments!

**Comment by jmhbnz** [comment]
Thanks for ticking all these off so quickly team, nice work.

**Comment by ivanvc** [comment]
@jmhbnz, when I started picking up this task, we listed only three repos: etcd, raft and bbolt. Should we start adding more repos? Do you suggest including gofail and auger from now on? (Some repositories tbh I never checked what they do :see_no_evil:)

Link to etcd-io/auger#91

**Comment by jmhbnz** [comment]
> @jmhbnz, when I started picking up this task, we listed only three repos: etcd, raft and bbolt. Should we start adding more repos? Do you suggest including gofail and auger from now on? 

It is less critical that we update gofail and auger in such a timely fashion, our big three repositories, `etcd`, `bbolt`, and `raft` should continue to be prioritised. If you have time to include others in planning please feel free.
