### ISSUE TITLE
Update main branch to Go 1.23 / release branches to 1.22

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#18443]
### What would you like to be added?

Go 1.23.0 was released yesterday. Therefore, Go 1.21 will be out of support when 1.24.0 is released. We should update the main branches to Go 1.23 and the release branches to 1.22.

Completion tracking below:

- [ ] `etcd/main`: #18444
- [x] `etcd/release-3.5`: #18445
- [x] `etcd/release-3.4`: #18445
- [x] `bbolt/main`: etcd-io/bbolt#821
- [x] `bbolt/release-1.3`: etcd-io/bbolt#822
- [x] `raft/main`: etcd-io/raft#212
- [x] `gofail/main`: etcd-io/gofail#78
- [x] `auger/main`: etcd-io/auger#96
- [ ] `CHANGELOG`s

### Why is this needed?

To keep the project up to date with the latest released Go version and run on supported versions.

**Comment by henrybear327** [comment]
There is an issue with the `golangci-lint` tool that I will need to deal with.

**Comment by jmhbnz** [comment]
> @jmhbnz, should we lower the priority due to [#18444 (comment)](https://github.com/etcd-io/etcd/pull/18444#issuecomment-2289978906)?

I think priority is still `important/soon` but it's ok to wait a little bit for the devcontainer to be published in order to update `etcd-io/main`.  We can proceed with updating to go 1.22 for stable release branches in the interim imo.

**Comment by henrybear327** [comment]
> > @jmhbnz, should we lower the priority due to [#18444 (comment)](https://github.com/etcd-io/etcd/pull/18444#issuecomment-2289978906)?
> 
> I think priority is still `important/soon` but it's ok to wait a little bit for the devcontainer to be published in order to update `etcd-io/main`. We can proceed with updating to go 1.22 for stable release branches in the interim imo.

How about we update the devcontainer as a subsequent step? 

I am not sure how long it will take the devcontainer team to release the new Go version ... :(

**Comment by henrybear327** [comment]
@jmhbnz @ivanvc @ahrtr Currently only the main etcd branch is still undergoing changes to fix the CI pipeline, but all other PRs should be ready for review!! :)

**Comment by ahrtr** [comment]
@henrybear327 Please raise a PR to update changelog for 3.4 and 3.5. thanks

**Comment by ivanvc** [comment]
Closing, as https://github.com/etcd-io/etcd/issues/18548 supersedes this issue. I'll update the CHANGELOG once we close the 3.4 and 3.5 pull requests.

**Comment by henrybear327** [comment]
> @henrybear327 Please raise a PR to update changelog for 3.4 and 3.5. thanks

Sorry that I definitely missed this comment...
