### ISSUE TITLE
Update Go to 1.23.2/1.22.8

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/etcd#18665]
### What would you like to be added?

Golang 1.23.2 and 1.22.8 were released today. According to our [Dependency management documentation](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md#golang-versions), we want to stay on the latest patch version. This means updating the `release-3.4` and `release-3.5` branches to 1.22.8 and `main` to 1.23.2.

Completion tracking below:

- [x] [`main`](https://github.com/etcd-io/etcd/tree/main): go v1.23.2 https://github.com/etcd-io/etcd/pull/18666
- [x] [`release-3.5`](https://github.com/etcd-io/etcd/tree/release-3.5): go v1.22.8 #18669
- [x] [`release-3.4`](https://github.com/etcd-io/etcd/tree/release-3.4): go v1.22.8 #18670
- [x] [`CHANGELOG`](https://github.com/etcd-io/etcd/tree/main/CHANGELOG): #18743
- [x] [`etcd-io/bbolt` `main`](https://github.com/etcd-io/bbolt/tree/main): go v1.23.2 etcd-io/bbolt#836
- [x] [`etcd-io/bbolt` `release-1.3`](https://github.com/etcd-io/bbolt/tree/releae-1.3): v1.22.8 etcd-io/bbolt#837
- [x] [`etcd-io/raft` `main`](https://github.com/etcd-io/raft/tree/main): go v1.23.2: https://github.com/etcd-io/raft/pull/228
- [x] [`etcd-io/gofail` `main`](https://github.com/etcd-io/gofail/tree/main): go v1.23.2 - etcd-io/gofail#85
- [x] [`etcd-io/auger` `main`](https://github.com/etcd-io/auger/tree/main): go v1.23.2 - etcd-io/auger#137

Refer to previous issues and their pull requests as a reference, i.e., #18443 and #18269.

### Why is this needed?

To keep the project up to date with the latest Go versions.

**Comment by ivanvc** [comment]
Hi @PyAgni, thanks for the PR against the main branch. Would you like to help with the remaining tasks, or should we open them to other contributors?

**Comment by PyAgni** [comment]
@ivanvc I can work on others as well. I will raise the PRs in some time.

**Comment by ivanvc** [comment]
Hi, again, @PyAgni. Thanks for the work you have done on this task. I was checking to see if you want to work on the remaining tasks or if we should open this up to other contributors.

**Comment by ivanvc** [comment]
I'll complete the remaining tasks

/assign

**Comment by ivanvc** [comment]
@henrybear327, do you want to help with auger and gofail?

**Comment by henrybear327** [comment]
> @henrybear327, do you want to help with auger and gofail?

Yes!

**Comment by henrybear327** [comment]
As [gofail](https://github.com/etcd-io/gofail/pull/85) and [auger](https://github.com/etcd-io/auger/pull/137) have been bumped and merged, @ivanvc can you update the PR description and close this issue :) 

Thank you and have a nice weekend!

**Comment by ivanvc** [comment]
Thanks for your work, team (@PyAgni, @henrybear327). Closing, as there are no more tasks remaining :raised_hands:
